const qna = [
{num: 1, que: "What is the Spanish verb for 'to speak'?", true: "hablar", false1: "comer", false2: "vivir"},
{num: 2, que: "What is the Spanish verb for 'to eat'?", true: "comer", false1: "beber", false2: "correr"},
{num: 3, que: "What is the Spanish verb for 'to live'?", true: "vivir", false1: "trabajar", false2: "estudiar"},
{num: 4, que: "What is the Spanish verb for 'to be (permanent)'?", true: "ser", false1: "estar", false2: "tener"},
{num: 5, que: "What is the Spanish verb for 'to be (temporary)'?", true: "estar", false1: "ser", false2: "hacer"},
{num: 6, que: "What is the Spanish verb for 'to have'?", true: "tener", false1: "hacer", false2: "poner"},
{num: 7, que: "What is the Spanish verb for 'to do/make'?", true: "hacer", false1: "decir", false2: "ver"},
{num: 8, que: "What is the Spanish verb for 'to go'?", true: "ir", false1: "venir", false2: "salir"},
{num: 9, que: "What is the Spanish verb for 'to come'?", true: "venir", false1: "ir", false2: "llegar"},
{num: 10, que: "What is the Spanish verb for 'to see'?", true: "ver", false1: "mirar", false2: "buscar"},
{num: 11, que: "What is the Spanish verb for 'to say/tell'?", true: "decir", false1: "hablar", false2: "contar"},
{num: 12, que: "What is the Spanish verb for 'to give'?", true: "dar", false1: "tomar", false2: "recibir"},
{num: 13, que: "What is the Spanish verb for 'to know (facts)'?", true: "saber", false1: "conocer", false2: "aprender"},
{num: 14, que: "What is the Spanish verb for 'to know (people/places)'?", true: "conocer", false1: "saber", false2: "encontrar"},
{num: 15, que: "What is the Spanish verb for 'to want'?", true: "querer", false1: "necesitar", false2: "desear"},
{num: 16, que: "What is the Spanish verb for 'to be able to'?", true: "poder", false1: "deber", false2: "necesitar"},
{num: 17, que: "What is the Spanish verb for 'to put/place'?", true: "poner", false1: "tomar", false2: "dejar"},
{num: 18, que: "What is the Spanish verb for 'to seem/appear'?", true: "parecer", false1: "aparecer", false2: "mostrar"},
{num: 19, que: "What is the Spanish verb for 'to believe'?", true: "creer", false1: "pensar", false2: "saber"},
{num: 20, que: "What is the Spanish verb for 'to follow/continue'?", true: "seguir", false1: "continuar", false2: "empezar"},
{num: 21, que: "What is the Spanish verb for 'to find'?", true: "encontrar", false1: "buscar", false2: "perder"},
{num: 22, que: "What is the Spanish verb for 'to call'?", true: "llamar", false1: "gritar", false2: "hablar"},
{num: 23, que: "What is the Spanish verb for 'to leave'?", true: "dejar", false1: "salir", false2: "llegar"},
{num: 24, que: "What is the Spanish verb for 'to take/drink'?", true: "tomar", false1: "dar", false2: "recibir"},
{num: 25, que: "What is the Spanish verb for 'to work'?", true: "trabajar", false1: "estudiar", false2: "aprender"},
{num: 26, que: "What is the Spanish verb for 'to need'?", true: "necesitar", false1: "querer", false2: "desear"},
{num: 27, que: "What is the Spanish verb for 'to feel'?", true: "sentir", false1: "pensar", false2: "creer"},
{num: 28, que: "What is the Spanish verb for 'to become'?", true: "llegar a ser", false1: "empezar a", false2: "terminar de"},
{num: 29, que: "What is the Spanish verb for 'to carry/wear'?", true: "llevar", false1: "traer", false2: "tener"},
{num: 30, que: "What is the Spanish verb for 'to pass/happen'?", true: "pasar", false1: "ocurrir", false2: "suceder"},
{num: 31, que: "What is the Spanish verb for 'to should/must'?", true: "deber", false1: "poder", false2: "querer"},
{num: 32, que: "What is the Spanish verb for 'to stay/remain'?", true: "quedar", false1: "estar", false2: "quedarse"},
{num: 33, que: "What is the Spanish verb for 'to think'?", true: "pensar", false1: "creer", false2: "saber"},
{num: 34, que: "What is the Spanish verb for 'to return'?", true: "volver", false1: "regresar", false2: "venir"},
{num: 35, que: "What is the Spanish verb for 'to recognize'?", true: "reconocer", false1: "conocer", false2: "saber"},
{num: 36, que: "What is the Spanish verb for 'to look/watch'?", true: "mirar", false1: "ver", false2: "buscar"},
{num: 37, que: "What is the Spanish verb for 'to obtain/get'?", true: "obtener", false1: "conseguir", false2: "recibir"},
{num: 38, que: "What is the Spanish verb for 'to begin/start'?", true: "empezar", false1: "comenzar", false2: "terminar"},
{num: 39, que: "What is the Spanish verb for 'to serve'?", true: "servir", false1: "ayudar", false2: "trabajar"},
{num: 40, que: "What is the Spanish verb for 'to speak/talk'?", true: "hablar", false1: "decir", false2: "contar"},
{num: 41, que: "What is the Spanish verb for 'to use'?", true: "usar", false1: "utilizar", false2: "necesitar"},
{num: 42, que: "What is the Spanish verb for 'to realize'?", true: "darse cuenta", false1: "entender", false2: "saber"},
{num: 43, que: "What is the Spanish verb for 'to read'?", true: "leer", false1: "escribir", false2: "estudiar"},
{num: 44, que: "What is the Spanish verb for 'to lose'?", true: "perder", false1: "ganar", false2: "encontrar"},
{num: 45, que: "What is the Spanish verb for 'to create'?", true: "crear", false1: "hacer", false2: "construir"},
{num: 46, que: "What is the Spanish verb for 'to explain'?", true: "explicar", false1: "entender", false2: "aprender"},
{num: 47, que: "What is the Spanish verb for 'to understand'?", true: "entender", false1: "comprender", false2: "saber"},
{num: 48, que: "What is the Spanish verb for 'to ask for/request'?", true: "pedir", false1: "preguntar", false2: "decir"},
{num: 49, que: "What is the Spanish verb for 'to remember'?", true: "recordar", false1: "acordarse", false2: "pensar"},
{num: 50, que: "What is the Spanish verb for 'to appear/show up'?", true: "aparecer", false1: "parecer", false2: "mostrar"},
{num: 51, que: "What is the Spanish verb for 'to wait for'?", true: "esperar", false1: "esperarse", false2: "quedar"},
{num: 52, que: "What is the Spanish verb for 'to consider'?", true: "considerar", false1: "pensar", false2: "creer"},
{num: 53, que: "What is the Spanish verb for 'to open'?", true: "abrir", false1: "cerrar", false2: "entrar"},
{num: 54, que: "What is the Spanish verb for 'to continue'?", true: "continuar", false1: "seguir", false2: "empezar"},
{num: 55, que: "What is the Spanish verb for 'to hear'?", true: "oír", false1: "escuchar", false2: "oir"},
{num: 56, que: "What is the Spanish verb for 'to walk'?", true: "caminar", false1: "andar", false2: "correr"},
{num: 57, que: "What is the Spanish verb for 'to write'?", true: "escribir", false1: "leer", false2: "estudiar"},
{num: 58, que: "What is the Spanish verb for 'to provide'?", true: "proveer", false1: "dar", false2: "ofrecer"},
{num: 59, que: "What is the Spanish verb for 'to sit down'?", true: "sentarse", false1: "sentir", false2: "estar"},
{num: 60, que: "What is the Spanish verb for 'to stand up'?", true: "levantarse", false1: "pararse", false2: "subir"},
{num: 61, que: "What is the Spanish verb for 'to try/attempt'?", true: "intentar", false1: "tratar", false2: "probar"},
{num: 62, que: "What is the Spanish verb for 'to change'?", true: "cambiar", false1: "cambiarse", false2: "volver"},
{num: 63, que: "What is the Spanish verb for 'to die'?", true: "morir", false1: "matar", false2: "perder"},
{num: 64, que: "What is the Spanish verb for 'to be born'?", true: "nacer", false1: "vivir", false2: "empezar"},
{num: 65, que: "What is the Spanish verb for 'to run'?", true: "correr", false1: "caminar", false2: "andar"},
{num: 66, que: "What is the Spanish verb for 'to travel'?", true: "viajar", false1: "visitar", false2: "conocer"},
{num: 67, que: "What is the Spanish verb for 'to play (a game)'?", true: "jugar", false1: "tocar", false2: "ganar"},
{num: 68, que: "What is the Spanish verb for 'to play (an instrument)'?", true: "tocar", false1: "jugar", false2: "cantar"},
{num: 69, que: "What is the Spanish verb for 'to sing'?", true: "cantar", false1: "bailar", false2: "escuchar"},
{num: 70, que: "What is the Spanish verb for 'to dance'?", true: "bailar", false1: "cantar", false2: "mover"},
{num: 71, que: "What is the Spanish verb for 'to study'?", true: "estudiar", false1: "aprender", false2: "enseñar"},
{num: 72, que: "What is the Spanish verb for 'to learn'?", true: "aprender", false1: "estudiar", false2: "entender"},
{num: 73, que: "What is the Spanish verb for 'to teach'?", true: "enseñar", false1: "aprender", false2: "estudiar"},
{num: 74, que: "What is the Spanish verb for 'to answer'?", true: "responder", false1: "preguntar", false2: "decir"},
{num: 75, que: "What is the Spanish verb for 'to ask (a question)'?", true: "preguntar", false1: "pedir", false2: "decir"},
{num: 76, que: "What is the Spanish verb for 'to help'?", true: "ayudar", false1: "necesitar", false2: "servir"},
{num: 77, que: "What is the Spanish verb for 'to love'?", true: "amar", false1: "querer", false2: "gustar"},
{num: 78, que: "What is the Spanish verb for 'to like'?", true: "gustar", false1: "amar", false2: "querer"},
{num: 79, que: "What is the Spanish verb for 'to look for'?", true: "buscar", false1: "encontrar", false2: "mirar"},
{num: 80, que: "What is the Spanish verb for 'to enter'?", true: "entrar", false1: "salir", false2: "llegar"},
{num: 81, que: "What is the Spanish verb for 'to exit/leave'?", true: "salir", false1: "entrar", false2: "llegar"},
{num: 82, que: "What is the Spanish verb for 'to arrive'?", true: "llegar", false1: "salir", false2: "ir"},
{num: 83, que: "What is the Spanish verb for 'to close'?", true: "cerrar", false1: "abrir", false2: "terminar"},
{num: 84, que: "What is the Spanish verb for 'to begin'?", true: "comenzar", false1: "empezar", false2: "terminar"},
{num: 85, que: "What is the Spanish verb for 'to finish'?", true: "terminar", false1: "acabar", false2: "comenzar"},
{num: 86, que: "What is the Spanish verb for 'to sleep'?", true: "dormir", false1: "soñar", false2: "descansar"},
{num: 87, que: "What is the Spanish verb for 'to wake up'?", true: "despertarse", false1: "despertar", false2: "levantarse"},
{num: 88, que: "What is the Spanish verb for 'to buy'?", true: "comprar", false1: "vender", false2: "pagar"},
{num: 89, que: "What is the Spanish verb for 'to sell'?", true: "vender", false1: "comprar", false2: "ganar"},
{num: 90, que: "What is the Spanish verb for 'to pay'?", true: "pagar", false1: "comprar", false2: "ganar"},
{num: 91, que: "What is the Spanish verb for 'to cost'?", true: "costar", false1: "valer", false2: "pagar"},
{num: 92, que: "What is the Spanish verb for 'to rain'?", true: "llover", false1: "nevar", false2: "hacer"},
{num: 93, que: "What is the Spanish verb for 'to snow'?", true: "nevar", false1: "llover", false2: "hacer"},
{num: 94, que: "What is the Spanish verb for 'to listen'?", true: "escuchar", false1: "oír", false2: "hablar"},
{num: 95, que: "What is the Spanish verb for 'to bring'?", true: "traer", false1: "llevar", false2: "tener"},
{num: 96, que: "What is the Spanish verb for 'to forget'?", true: "olvidar", false1: "olvidarse", false2: "recordar"},
{num: 97, que: "What is the Spanish verb for 'to prefer'?", true: "preferir", false1: "querer", false2: "gustar"},
{num: 98, que: "What is the Spanish verb for 'to send'?", true: "enviar", false1: "mandar", false2: "dar"},
{num: 99, que: "What is the Spanish verb for 'to receive'?", true: "recibir", false1: "tomar", false2: "dar"},
{num: 100, que: "What is the Spanish verb for 'to offer'?", true: "ofrecer", false1: "dar", false2: "recibir"},

    // Second 100: Verb Tenses (focusing on most common verbs)
    // Present Tense
    {num: 101, que: "What is the correct conjugation for 'Present: yo (hablar)'?", true: "hablo", false1: "habla", false2: "hablan"},
    {num: 102, que: "What is the correct conjugation for 'Present: tú (comer)'?", true: "comes", false1: "come", false2: "comemos"},
    {num: 103, que: "What is the correct conjugation for 'Present: él/ella (vivir)'?", true: "vive", false1: "vivo", false2: "vives"},
    {num: 104, que: "What is the correct conjugation for 'Present: nosotros (ser)'?", true: "somos", false1: "sois", false2: "son"},
    {num: 105, que: "What is the correct conjugation for 'Present: ellos (tener)'?", true: "tienen", false1: "tenemos", false2: "tengo"},
    {num: 106, que: "What is the correct conjugation for 'Present: yo (hacer)'?", true: "hago", false1: "hace", false2: "hacen"},
    {num: 107, que: "What is the correct conjugation for 'Present: tú (ir)'?", true: "vas", false1: "va", false2: "voy"},
    {num: 108, que: "What is the correct conjugation for 'Present: yo (ver)'?", true: "veo", false1: "ves", false2: "ven"},
    {num: 109, que: "What is the correct conjugation for 'Present: él/ella (decir)'?", true: "dice", false1: "digo", false2: "dicen"},
    {num: 110, que: "What is the correct conjugation for 'Present: yo (querer)'?", true: "quiero", false1: "quiere", false2: "quieren"},

    // Preterite (Past Simple)
    {num: 111, que: "What is the correct conjugation for 'Preterite: yo (hablar)'?", true: "hablé", false1: "hablaba", false2: "hablo"},
    {num: 112, que: "What is the correct conjugation for 'Preterite: tú (comer)'?", true: "comiste", false1: "comías", false2: "comes"},
    {num: 113, que: "What is the correct conjugation for 'Preterite: él/ella (vivir)'?", true: "vivió", false1: "vivía", false2: "vive"},
    {num: 114, que: "What is the correct conjugation for 'Preterite: nosotros (ser)'?", true: "fuimos", false1: "éramos", false2: "somos"},
    {num: 115, que: "What is the correct conjugation for 'Preterite: ellos (tener)'?", true: "tuvieron", false1: "tenían", false2: "tienen"},
    {num: 116, que: "What is the correct conjugation for 'Preterite: yo (hacer)'?", true: "hice", false1: "hacía", false2: "hago"},
    {num: 117, que: "What is the correct conjugation for 'Preterite: tú (ir)'?", true: "fuiste", false1: "ibas", false2: "vas"},
    {num: 118, que: "What is the correct conjugation for 'Preterite: él/ella (ver)'?", true: "vio", false1: "veía", false2: "ve"},
    {num: 119, que: "What is the correct conjugation for 'Preterite: yo (decir)'?", true: "dije", false1: "decía", false2: "digo"},
    {num: 120, que: "What is the correct conjugation for 'Preterite: tú (querer)'?", true: "quisiste", false1: "querías", false2: "quieres"},

    // Imperfect
    {num: 121, que: "What is the correct conjugation for 'Imperfect: yo (hablar)'?", true: "hablaba", false1: "hablé", false2: "hablo"},
    {num: 122, que: "What is the correct conjugation for 'Imperfect: tú (comer)'?", true: "comías", false1: "comiste", false2: "comes"},
    {num: 123, que: "What is the correct conjugation for 'Imperfect: él/ella (vivir)'?", true: "vivía", false1: "vivió", false2: "vive"},
    {num: 124, que: "What is the correct conjugation for 'Imperfect: nosotros (ser)'?", true: "éramos", false1: "fuimos", false2: "somos"},
    {num: 125, que: "What is the correct conjugation for 'Imperfect: ellos (tener)'?", true: "tenían", false1: "tuvieron", false2: "tienen"},
    {num: 126, que: "What is the correct conjugation for 'Imperfect: yo (hacer)'?", true: "hacía", false1: "hice", false2: "hago"},
    {num: 127, que: "What is the correct conjugation for 'Imperfect: tú (ir)'?", true: "ibas", false1: "fuiste", false2: "vas"},
    {num: 128, que: "What is the correct conjugation for 'Imperfect: él/ella (ver)'?", true: "veía", false1: "vio", false2: "ve"},
    {num: 129, que: "What is the correct conjugation for 'Imperfect: yo (decir)'?", true: "decía", false1: "dije", false2: "digo"},
    {num: 130, que: "What is the correct conjugation for 'Imperfect: tú (querer)'?", true: "querías", false1: "quisiste", false2: "quieres"},

    // Future
    {num: 131, que: "What is the correct conjugation for 'Future: yo (hablar)'?", true: "hablaré", false1: "hablo", false2: "hablaba"},
    {num: 132, que: "What is the correct conjugation for 'Future: tú (comer)'?", true: "comerás", false1: "comes", false2: "comías"},
    {num: 133, que: "What is the correct conjugation for 'Future: él/ella (vivir)'?", true: "vivirá", false1: "vive", false2: "vivía"},
    {num: 134, que: "What is the correct conjugation for 'Future: nosotros (ser)'?", true: "seremos", false1: "somos", false2: "éramos"},
    {num: 135, que: "What is the correct conjugation for 'Future: ellos (tener)'?", true: "tendrán", false1: "tienen", false2: "tenían"},
    {num: 136, que: "What is the correct conjugation for 'Future: yo (hacer)'?", true: "haré", false1: "hago", false2: "hacía"},
    {num: 137, que: "What is the correct conjugation for 'Future: tú (ir)'?", true: "irás", false1: "vas", false2: "ibas"},
    {num: 138, que: "What is the correct conjugation for 'Future: él/ella (ver)'?", true: "verá", false1: "ve", false2: "veía"},
    {num: 139, que: "What is the correct conjugation for 'Future: yo (decir)'?", true: "diré", false1: "digo", false2: "decía"},
    {num: 140, que: "What is the correct conjugation for 'Future: tú (querer)'?", true: "querrás", false1: "quieres", false2: "querías"},

    // Conditional
    {num: 141, que: "What is the correct conjugation for 'Conditional: yo (hablar)'?", true: "hablaría", false1: "hablo", false2: "hablaré"},
    {num: 142, que: "What is the correct conjugation for 'Conditional: tú (comer)'?", true: "comerías", false1: "comes", false2: "comerás"},
    {num: 143, que: "What is the correct conjugation for 'Conditional: él/ella (vivir)'?", true: "viviría", false1: "vive", false2: "vivirá"},
    {num: 144, que: "What is the correct conjugation for 'Conditional: nosotros (ser)'?", true: "seríamos", false1: "somos", false2: "seremos"},
    {num: 145, que: "What is the correct conjugation for 'Conditional: ellos (tener)'?", true: "tendrían", false1: "tienen", false2: "tendrán"},
    {num: 146, que: "What is the correct conjugation for 'Conditional: yo (hacer)'?", true: "haría", false1: "hago", false2: "haré"},
    {num: 147, que: "What is the correct conjugation for 'Conditional: tú (ir)'?", true: "irías", false1: "vas", false2: "irás"},
    {num: 148, que: "What is the correct conjugation for 'Conditional: él/ella (ver)'?", true: "vería", false1: "ve", false2: "verá"},
    {num: 149, que: "What is the correct conjugation for 'Conditional: yo (decir)'?", true: "diría", false1: "digo", false2: "diré"},
    {num: 150, que: "What is the correct conjugation for 'Conditional: tú (querer)'?", true: "querrías", false1: "quieres", false2: "querrás"},

    // Present Subjunctive
    {num: 151, que: "What is the correct conjugation for 'Subjunctive: yo (hablar)'?", true: "hable", false1: "hablo", false2: "hablé"},
    {num: 152, que: "What is the correct conjugation for 'Subjunctive: tú (comer)'?", true: "comas", false1: "comes", false2: "comiste"},
    {num: 153, que: "What is the correct conjugation for 'Subjunctive: él/ella (vivir)'?", true: "viva", false1: "vive", false2: "vivió"},
    {num: 154, que: "What is the correct conjugation for 'Subjunctive: nosotros (ser)'?", true: "seamos", false1: "somos", false2: "fuimos"},
    {num: 155, que: "What is the correct conjugation for 'Subjunctive: ellos (tener)'?", true: "tengan", false1: "tienen", false2: "tuvieron"},
    {num: 156, que: "What is the correct conjugation for 'Subjunctive: yo (hacer)'?", true: "haga", false1: "hago", false2: "hice"},
    {num: 157, que: "What is the correct conjugation for 'Subjunctive: tú (ir)'?", true: "vayas", false1: "vas", false2: "fuiste"},
    {num: 158, que: "What is the correct conjugation for 'Subjunctive: él/ella (ver)'?", true: "vea", false1: "ve", false2: "vio"},
    {num: 159, que: "What is the correct conjugation for 'Subjunctive: yo (decir)'?", true: "diga", false1: "digo", false2: "dije"},
    {num: 160, que: "What is the correct conjugation for 'Subjunctive: tú (querer)'?", true: "quieras", false1: "quieres", false2: "quisiste"},

    // More mixed tenses for important verbs
    {num: 161, que: "What is the correct conjugation for 'Present: yo (poder)'?", true: "puedo", false1: "puede", false2: "pueden"},
    {num: 162, que: "What is the correct conjugation for 'Preterite: él/ella (poder)'?", true: "pudo", false1: "podía", false2: "puede"},
    {num: 163, que: "What is the correct conjugation for 'Present: tú (saber)'?", true: "sabes", false1: "sabe", false2: "saben"},
    {num: 164, que: "What is the correct conjugation for 'Preterite: yo (saber)'?", true: "supe", false1: "sabía", false2: "sé"},
    {num: 165, que: "What is the correct conjugation for 'Present: él/ella (poner)'?", true: "pone", false1: "pono", false2: "ponen"},
    {num: 166, que: "What is the correct conjugation for 'Preterite: tú (poner)'?", true: "pusiste", false1: "ponías", false2: "pones"},
    {num: 167, que: "What is the correct conjugation for 'Present: yo (salir)'?", true: "salgo", false1: "salo", false2: "sale"},
    {num: 168, que: "What is the correct conjugation for 'Future: él/ella (salir)'?", true: "saldrá", false1: "sale", false2: "salía"},
    {num: 169, que: "What is the correct conjugation for 'Present: tú (venir)'?", true: "vienes", false1: "viene", false2: "vienen"},
    {num: 170, que: "What is the correct conjugation for 'Preterite: yo (venir)'?", true: "vine", false1: "venía", false2: "vengo"},

    // Additional important verb tenses
    {num: 171, que: "What is the correct conjugation for 'Present: él/ella (conocer)'?", true: "conoce", false1: "conozco", false2: "conocen"},
    {num: 172, que: "What is the correct conjugation for 'Preterite: tú (conocer)'?", true: "conociste", false1: "conocías", false2: "conoces"},
    {num: 173, que: "What is the correct conjugation for 'Present: yo (dar)'?", true: "doy", false1: "da", false2: "dan"},
    {num: 174, que: "What is the correct conjugation for 'Imperfect: él/ella (dar)'?", true: "daba", false1: "dio", false2: "da"},
    {num: 175, que: "What is the correct conjugation for 'Present: tú (estar)'?", true: "estás", false1: "está", false2: "están"},
    {num: 176, que: "What is the correct conjugation for 'Preterite: él/ella (estar)'?", true: "estuvo", false1: "estaba", false2: "está"},
    {num: 177, que: "What is the correct conjugation for 'Present: yo (pensar)'?", true: "pienso", false1: "piensa", false2: "piensan"},
    {num: 178, que: "What is the correct conjugation for 'Future: tú (pensar)'?", true: "pensarás", false1: "piensas", false2: "pensabas"},
    {num: 179, que: "What is the correct conjugation for 'Present: él/ella (encontrar)'?", true: "encuentra", false1: "encuentro", false2: "encuentran"},
    {num: 180, que: "What is the correct conjugation for 'Preterite: yo (encontrar)'?", true: "encontré", false1: "encontraba", false2: "encuentro"},

    // Last 20 mixed tense questions
    {num: 181, que: "What is the correct conjugation for 'Present: nosotros (volver)'?", true: "volvemos", false1: "volvimos", false2: "volveremos"},
    {num: 182, que: "What is the correct conjugation for 'Preterite: ellos (volver)'?", true: "volvieron", false1: "volvían", false2: "vuelven"},
    {num: 183, que: "What is the correct conjugation for 'Present: yo (pedir)'?", true: "pido", false1: "pide", false2: "piden"},
    {num: 184, que: "What is the correct conjugation for 'Imperfect: tú (pedir)'?", true: "pedías", false1: "pediste", false2: "pides"},
    {num: 185, que: "What is the correct conjugation for 'Present: él/ella (sentir)'?", true: "siente", false1: "siento", false2: "sienten"},
    {num: 186, que: "What is the correct conjugation for 'Future: yo (sentir)'?", true: "sentiré", false1: "siento", false2: "sentía"},
    {num: 187, que: "What is the correct conjugation for 'Present: tú (dormir)'?", true: "duermes", false1: "duerme", false2: "duermen"},
    {num: 188, que: "What is the correct conjugation for 'Preterite: él/ella (dormir)'?", true: "durmió", false1: "dormía", false2: "duerme"},
    {num: 189, que: "What is the correct conjugation for 'Present: yo (jugar)'?", true: "juego", false1: "juega", false2: "juegan"},
    {num: 190, que: "What is the correct conjugation for 'Imperfect: tú (jugar)'?", true: "jugabas", false1: "jugaste", false2: "juegas"},
    {num: 191, que: "What is the correct conjugation for 'Present: él/ella (empezar)'?", true: "empieza", false1: "empiezo", false2: "empiezan"},
    {num: 192, que: "What is the correct conjugation for 'Future: nosotros (empezar)'?", true: "empezaremos", false1: "empezamos", false2: "empezábamos"},
    {num: 193, que: "What is the correct conjugation for 'Present: yo (entender)'?", true: "entiendo", false1: "entiende", false2: "entienden"},
    {num: 194, que: "What is the correct conjugation for 'Preterite: tú (entender)'?", true: "entendiste", false1: "entendías", false2: "entiendes"},
    {num: 195, que: "What is the correct conjugation for 'Present: él/ella (perder)'?", true: "pierde", false1: "pierdo", false2: "pierden"},
    {num: 196, que: "What is the correct conjugation for 'Conditional: yo (perder)'?", true: "perdería", false1: "pierdo", false2: "perderé"},
    {num: 197, que: "What is the correct conjugation for 'Present: tú (preferir)'?", true: "prefieres", false1: "prefiere", false2: "prefieren"},
    {num: 198, que: "What is the correct conjugation for 'Imperfect: él/ella (preferir)'?", true: "prefería", false1: "prefirió", false2: "prefiere"},
    {num: 199, que: "What is the correct conjugation for 'Present: yo (seguir)'?", true: "sigo", false1: "sigue", false2: "siguen"},
    {num: 200, que: "What is the correct conjugation for 'Future: tú (seguir)'?", true: "seguirás", false1: "sigues", false2: "seguías"},
    {num: 1, que: "What is the Spanish preposition for 'of / from'?", true: "de", false1: "a", false2: "en"},
{num: 2, que: "What is the Spanish preposition for 'to / at'?", true: "a", false1: "de", false2: "en"},
{num: 3, que: "What is the Spanish preposition for 'in / on / at'?", true: "en", false1: "a", false2: "de"},
{num: 4, que: "What is the Spanish word for 'with'?", true: "con", false1: "sin", false2: "por"},
{num: 5, que: "What is the Spanish word for 'without'?", true: "sin", false1: "con", false2: "sobre"},
{num: 6, que: "What is the Spanish preposition for 'for / through / by'?", true: "por", false1: "para", false2: "según"},
{num: 7, que: "What is the Spanish preposition for 'for / in order to'?", true: "para", false1: "por", false2: "hasta"},
{num: 8, que: "What is the Spanish phrase for 'under'?", true: "debajo de", false1: "sobre", false2: "entre"},
{num: 9, que: "What is the Spanish word for 'over / above / on'?", true: "sobre", false1: "bajo", false2: "entre"},
{num: 10, que: "What is the Spanish word for 'between / among'?", true: "entre", false1: "hacia", false2: "según"},
{num: 11, que: "What is the Spanish word for 'toward'?", true: "hacia", false1: "hasta", false2: "desde"},
{num: 12, que: "What is the Spanish word for 'until / up to'?", true: "hasta", false1: "hacia", false2: "desde"},
{num: 13, que: "What is the Spanish word for 'from / since'?", true: "desde", false1: "hasta", false2: "hacia"},
{num: 14, que: "What is the Spanish word for 'against'?", true: "contra", false1: "frente a", false2: "según"},
{num: 15, que: "What is the Spanish phrase for 'according to'?", true: "según", false1: "contra", false2: "entre"},
{num: 16, que: "What is the Spanish phrase for 'behind'?", true: "detrás de", false1: "delante de", false2: "debajo de"},
{num: 17, que: "What is the Spanish phrase for 'in front of'?", true: "delante de", false1: "detrás de", false2: "encima de"},
{num: 18, que: "What is the Spanish phrase for 'next to / beside'?", true: "al lado de", false1: "cerca de", false2: "lejos de"},
{num: 19, que: "What is the Spanish phrase for 'near'?", true: "cerca de", false1: "lejos de", false2: "al lado de"},
{num: 20, que: "What is the Spanish phrase for 'far from'?", true: "lejos de", false1: "cerca de", false2: "al lado de"},
{num: 21, que: "What is the Spanish word for 'inside'?", true: "dentro de", false1: "fuera de", false2: "sobre"},
{num: 22, que: "What is the Spanish word for 'outside'?", true: "fuera de", false1: "dentro de", false2: "sobre"},
{num: 23, que: "What is the Spanish phrase for 'above / on top of'?", true: "encima de", false1: "debajo de", false2: "sobre"},
{num: 24, que: "What is the Spanish phrase for 'below / underneath'?", true: "debajo de", false1: "encima de", false2: "sobre"},
{num: 25, que: "What is the Spanish phrase for 'in front of / facing'?", true: "frente a", false1: "detrás de", false2: "al lado de"},
{num: 26, que: "What is the Spanish phrase for 'around'?", true: "alrededor de", false1: "a través de", false2: "sobre"},
{num: 27, que: "What is the Spanish phrase for 'across / through'?", true: "a través de", false1: "alrededor de", false2: "hacia"},
{num: 28, que: "What is the Spanish word for 'during'?", true: "durante", false1: "hasta", false2: "desde"},
{num: 29, que: "What is the Spanish phrase for 'after'?", true: "después de", false1: "antes de", false2: "durante"},
{num: 30, que: "What is the Spanish phrase for 'before'?", true: "antes de", false1: "después de", false2: "durante"},
{num: 31, que: "What is the Spanish word for 'much / many / a lot'?", true: "mucho", false1: "poco", false2: "bastante"},
{num: 32, que: "What is the Spanish word for 'little / few'?", true: "poco", false1: "mucho", false2: "bastante"},
{num: 33, que: "What is the Spanish word for 'some / a few'?", true: "alguno", false1: "ninguno", false2: "varios"},
{num: 34, que: "What is the Spanish word for 'none / not any'?", true: "ninguno", false1: "alguno", false2: "varios"},
{num: 35, que: "What is the Spanish word for 'several'?", true: "varios", false1: "alguno", false2: "ninguno"},
{num: 36, que: "What is the Spanish word for 'enough / sufficient'?", true: "bastante", false1: "mucho", false2: "poco"},
{num: 37, que: "What is the Spanish word for 'too much'?", true: "demasiado", false1: "bastante", false2: "mucho"},
{num: 38, que: "What is the Spanish word for 'more'?", true: "más", false1: "menos", false2: "mucho"},
{num: 39, que: "What is the Spanish word for 'less'?", true: "menos", false1: "más", false2: "poco"},
{num: 40, que: "What is the Spanish word for 'very'?", true: "muy", false1: "mucho", false2: "más"},
{num: 41, que: "What is the Spanish word for 'all / every'?", true: "todo", false1: "cada", false2: "alguno"},
{num: 42, que: "What is the Spanish word for 'each / every'?", true: "cada", false1: "todo", false2: "alguno"},
{num: 43, que: "What is the Spanish word for 'both'?", true: "ambos", false1: "todos", false2: "ninguno"},
{num: 44, que: "What is the Spanish word for 'only / just'?", true: "solo", false1: "todo", false2: "cada"},
{num: 45, que: "What is the Spanish word for 'even'?", true: "incluso", false1: "solo", false2: "también"},
{num: 46, que: "What is the Spanish word for 'also / too'?", true: "también", false1: "incluso", false2: "solo"},
{num: 47, que: "What is the Spanish word for 'almost / nearly'?", true: "casi", false1: "siempre", false2: "nunca"},
{num: 48, que: "What is the Spanish word for 'hardly / barely'?", true: "apenas", false1: "casi", false2: "siempre"},
{num: 49, que: "What is the Spanish word for 'always'?", true: "siempre", false1: "nunca", false2: "a veces"},
{num: 50, que: "What is the Spanish word for 'never'?", true: "nunca", false1: "siempre", false2: "a veces"},
{num: 51, que: "What is the Spanish phrase for 'sometimes'?", true: "a veces", false1: "siempre", false2: "nunca"},
{num: 52, que: "What is the Spanish phrase for 'often'?", true: "a menudo", false1: "rara vez", false2: "siempre"},
{num: 53, que: "What is the Spanish phrase for 'rarely / seldom'?", true: "rara vez", false1: "a menudo", false2: "siempre"},
{num: 54, que: "What is the Spanish phrase for 'almost all'?", true: "casi todo", false1: "todo", false2: "nada"},
{num: 55, que: "What is the Spanish word for 'nothing'?", true: "nada", false1: "nadie", false2: "ninguno"},
{num: 56, que: "What is the Spanish word for 'big / large'?", true: "grande", false1: "pequeño", false2: "mediano"},
{num: 57, que: "What is the Spanish word for 'small / little'?", true: "pequeño", false1: "grande", false2: "mediano"},
{num: 58, que: "What is the Spanish word for 'good'?", true: "bueno", false1: "malo", false2: "regular"},
{num: 59, que: "What is the Spanish word for 'bad'?", true: "malo", false1: "bueno", false2: "regular"},
{num: 60, que: "What is the Spanish word for 'beautiful'?", true: "hermoso", false1: "feo", false2: "bonito"},
{num: 61, que: "What is the Spanish word for 'ugly'?", true: "feo", false1: "hermoso", false2: "bonito"},
{num: 62, que: "What is the Spanish word for 'pretty / nice'?", true: "bonito", false1: "feo", false2: "hermoso"},
{num: 63, que: "What is the Spanish word for 'new'?", true: "nuevo", false1: "viejo", false2: "moderno"},
{num: 64, que: "What is the Spanish word for 'old'?", true: "viejo", false1: "nuevo", false2: "antiguo"},
{num: 65, que: "What is the Spanish word for 'young'?", true: "joven", false1: "viejo", false2: "nuevo"},
{num: 66, que: "What is the Spanish word for 'old (person)'?", true: "mayor", false1: "joven", false2: "viejo"},
{num: 67, que: "What is the Spanish word for 'easy'?", true: "fácil", false1: "difícil", false2: "simple"},
{num: 68, que: "What is the Spanish word for 'difficult'?", true: "difícil", false1: "fácil", false2: "complicado"},
{num: 69, que: "What is the Spanish word for 'important'?", true: "importante", false1: "necesario", false2: "útil"},
{num: 70, que: "What is the Spanish word for 'interesting'?", true: "interesante", false1: "aburrido", false2: "importante"},
{num: 71, que: "What is the Spanish word for 'boring'?", true: "aburrido", false1: "interesante", false2: "divertido"},
{num: 72, que: "What is the Spanish word for 'fun / funny'?", true: "divertido", false1: "aburrido", false2: "interesante"},
{num: 73, que: "What is the Spanish word for 'happy'?", true: "feliz", false1: "triste", false2: "contento"},
{num: 74, que: "What is the Spanish word for 'sad'?", true: "triste", false1: "feliz", false2: "contento"},
{num: 75, que: "What is the Spanish word for 'content / pleased'?", true: "contento", false1: "triste", false2: "feliz"},
{num: 76, que: "What is the Spanish word for 'angry'?", true: "enojado", false1: "tranquilo", false2: "nervioso"},
{num: 77, que: "What is the Spanish word for 'calm'?", true: "tranquilo", false1: "nervioso", false2: "enojado"},
{num: 78, que: "What is the Spanish word for 'nervous'?", true: "nervioso", false1: "tranquilo", false2: "enojado"},
{num: 79, que: "What is the Spanish word for 'tired'?", true: "cansado", false1: "descansado", false2: "enfermo"},
{num: 80, que: "What is the Spanish word for 'sick / ill'?", true: "enfermo", false1: "sano", false2: "cansado"},
{num: 81, que: "What is the Spanish word for 'healthy'?", true: "sano", false1: "enfermo", false2: "fuerte"},
{num: 82, que: "What is the Spanish word for 'strong'?", true: "fuerte", false1: "débil", false2: "sano"},
{num: 83, que: "What is the Spanish word for 'weak'?", true: "débil", false1: "fuerte", false2: "enfermo"},
{num: 84, que: "What is the Spanish word for 'rich'?", true: "rico", false1: "pobre", false2: "caro"},
{num: 85, que: "What is the Spanish word for 'poor'?", true: "pobre", false1: "rico", false2: "barato"},
{num: 86, que: "What is the Spanish word for 'expensive'?", true: "caro", false1: "barato", false2: "rico"},
{num: 87, que: "What is the Spanish word for 'cheap'?", true: "barato", false1: "caro", false2: "pobre"},
{num: 88, que: "What is the Spanish word for 'fast / quick'?", true: "rápido", false1: "lento", false2: "pronto"},
{num: 89, que: "What is the Spanish word for 'slow'?", true: "lento", false1: "rápido", false2: "tarde"},
{num: 90, que: "What is the Spanish word for 'early'?", true: "temprano", false1: "tarde", false2: "pronto"},
{num: 91, que: "What is the Spanish word for 'late'?", true: "tarde", false1: "temprano", false2: "lento"},
{num: 92, que: "What is the Spanish word for 'hot'?", true: "caliente", false1: "frío", false2: "cálido"},
{num: 93, que: "What is the Spanish word for 'cold'?", true: "frío", false1: "caliente", false2: "fresco"},
{num: 94, que: "What is the Spanish word for 'warm'?", true: "cálido", false1: "frío", false2: "caliente"},
{num: 95, que: "What is the Spanish word for 'cool'?", true: "fresco", false1: "caliente", false2: "frío"},
{num: 96, que: "What is the Spanish word for 'long'?", true: "largo", false1: "corto", false2: "alto"},
{num: 97, que: "What is the Spanish word for 'short'?", true: "corto", false1: "largo", false2: "bajo"},
{num: 98, que: "What is the Spanish word for 'tall / high'?", true: "alto", false1: "bajo", false2: "largo"},
{num: 99, que: "What is the Spanish word for 'short / low'?", true: "bajo", false1: "alto", false2: "corto"},
{num: 100, que: "What is the Spanish word for 'wide'?", true: "ancho", false1: "estrecho", false2: "largo"},
{num: 101, que: "What is the Spanish subject pronoun for 'I'?", true: "yo", false1: "mí", false2: "me"},
{num: 102, que: "What is the Spanish subject pronoun for 'you (informal)'?", true: "tú", false1: "usted", false2: "ti"},
{num: 103, que: "What is the Spanish subject pronoun for 'he'?", true: "él", false1: "ello", false2: "lo"},
{num: 104, que: "What is the Spanish subject pronoun for 'she'?", true: "ella", false1: "él", false2: "la"},
{num: 105, que: "What is the Spanish subject pronoun for 'you (formal)'?", true: "usted", false1: "tú", false2: "ti"},
{num: 106, que: "What is the Spanish subject pronoun for 'we'?", true: "nosotros", false1: "nosotras", false2: "nos"},
{num: 107, que: "What is the Spanish subject pronoun for 'they (masculine)'?", true: "ellos", false1: "ellas", false2: "los"},
{num: 108, que: "What is the Spanish subject pronoun for 'they (feminine)'?", true: "ellas", false1: "ellos", false2: "las"},
{num: 109, que: "What is the Spanish subject pronoun for 'you all (formal)'?", true: "ustedes", false1: "vosotros", false2: "vosotras"},
{num: 110, que: "What is the Spanish direct object pronoun for 'me'?", true: "me", false1: "mí", false2: "yo"},
{num: 111, que: "What is the Spanish direct object pronoun for 'you (informal)'?", true: "te", false1: "tú", false2: "ti"},
{num: 112, que: "What is the Spanish direct object pronoun for 'him / it'?", true: "lo", false1: "le", false2: "él"},
{num: 113, que: "What is the Spanish direct object pronoun for 'her / it'?", true: "la", false1: "le", false2: "ella"},
{num: 114, que: "What is the Spanish direct object pronoun for 'you (formal)'?", true: "lo/la", false1: "le", false2: "usted"},
{num: 115, que: "What is the Spanish direct object pronoun for 'us'?", true: "nos", false1: "nosotros", false2: "nosotras"},
{num: 116, que: "What is the Spanish direct object pronoun for 'them (masculine)'?", true: "los", false1: "les", false2: "ellos"},
{num: 117, que: "What is the Spanish direct object pronoun for 'them (feminine)'?", true: "las", false1: "les", false2: "ellas"},
{num: 118, que: "What is the Spanish indirect object pronoun for 'to/for me'?", true: "me", false1: "mí", false2: "yo"},
{num: 119, que: "What is the Spanish indirect object pronoun for 'to/for you (informal)'?", true: "te", false1: "tú", false2: "ti"},
{num: 120, que: "What is the Spanish indirect object pronoun for 'to/for him/her/you (formal)'?", true: "le", false1: "lo", false2: "la"},
{num: 121, que: "What is the Spanish indirect object pronoun for 'to/for us'?", true: "nos", false1: "nosotros", false2: "nosotras"},
{num: 122, que: "What is the Spanish indirect object pronoun for 'to/for them/you all'?", true: "les", false1: "los", false2: "las"},
{num: 123, que: "What is the Spanish reflexive pronoun for 'myself'?", true: "me", false1: "mí", false2: "yo"},
{num: 124, que: "What is the Spanish reflexive pronoun for 'yourself (informal)'?", true: "te", false1: "tú", false2: "ti"},
{num: 125, que: "What is the Spanish reflexive pronoun for 'himself/herself/yourself (formal)'?", true: "se", false1: "le", false2: "lo"},
{num: 126, que: "What is the Spanish reflexive pronoun for 'ourselves'?", true: "nos", false1: "nosotros", false2: "nosotras"},
{num: 127, que: "What is the Spanish reflexive pronoun for 'themselves/yourselves'?", true: "se", false1: "les", false2: "los"},
{num: 128, que: "What is the Spanish prepositional pronoun for 'me'?", true: "mí", false1: "me", false2: "yo"},
{num: 129, que: "What is the Spanish prepositional pronoun for 'you'?", true: "ti", false1: "te", false2: "tú"},
{num: 130, que: "What is the Spanish prepositional pronoun for 'him'?", true: "él", false1: "lo", false2: "le"},
{num: 131, que: "What is the Spanish prepositional pronoun for 'her'?", true: "ella", false1: "la", false2: "le"},
{num: 132, que: "What is the Spanish prepositional pronoun for 'us'?", true: "nosotros/nosotras", false1: "nos", false2: "nuestro"},
{num: 133, que: "What is the Spanish possessive adjective for 'my'?", true: "mi", false1: "mis", false2: "mío"},
{num: 134, que: "What is the Spanish possessive adjective for 'your (informal)'?", true: "tu", false1: "tus", false2: "tuyo"},
{num: 135, que: "What is the Spanish possessive adjective for 'his/her/your (formal)'?", true: "su", false1: "sus", false2: "suyo"},
{num: 136, que: "What is the Spanish possessive adjective for 'our'?", true: "nuestro", false1: "nuestra", false2: "nosotros"},
{num: 137, que: "What is the Spanish possessive adjective for 'their/your all'?", true: "su", false1: "sus", false2: "suyo"},
{num: 138, que: "What is the Spanish possessive pronoun for 'mine'?", true: "mío", false1: "mi", false2: "mis"},
{num: 139, que: "What is the Spanish possessive pronoun for 'yours (informal)'?", true: "tuyo", false1: "tu", false2: "tus"},
{num: 140, que: "What is the Spanish possessive pronoun for 'his/hers/yours (formal)'?", true: "suyo", false1: "su", false2: "sus"},
{num: 141, que: "What is the Spanish possessive pronoun for 'ours'?", true: "nuestro", false1: "nosotros", false2: "nos"},
{num: 142, que: "What is the Spanish possessive pronoun for 'theirs/yours all'?", true: "suyo", false1: "su", false2: "sus"},
{num: 143, que: "What is the Spanish demonstrative for 'this (masculine)'?", true: "este", false1: "ese", false2: "aquel"},
{num: 144, que: "What is the Spanish demonstrative for 'this (feminine)'?", true: "esta", false1: "esa", false2: "aquella"},
{num: 145, que: "What is the Spanish demonstrative for 'that (masculine - near)'?", true: "ese", false1: "este", false2: "aquel"},
{num: 146, que: "What is the Spanish demonstrative for 'that (feminine - near)'?", true: "esa", false1: "esta", false2: "aquella"},
{num: 147, que: "What is the Spanish demonstrative for 'that (masculine - far)'?", true: "aquel", false1: "ese", false2: "este"},
{num: 148, que: "What is the Spanish demonstrative for 'that (feminine - far)'?", true: "aquella", false1: "esa", false2: "esta"},
{num: 149, que: "What is the Spanish interrogative for 'what?'?", true: "qué", false1: "cuál", false2: "cómo"},
{num: 150, que: "What is the Spanish interrogative for 'who?'?", true: "quién", false1: "qué", false2: "cuál"},
{num: 151, que: "What is the Spanish interrogative for 'which?'?", true: "cuál", false1: "qué", false2: "quién"},
{num: 152, que: "What is the Spanish interrogative for 'how much/many?'?", true: "cuánto", false1: "qué", false2: "cómo"},
{num: 153, que: "What is the Spanish interrogative for 'where?'?", true: "dónde", false1: "cuándo", false2: "cómo"},
{num: 154, que: "What is the Spanish interrogative for 'when?'?", true: "cuándo", false1: "dónde", false2: "cómo"},
{num: 155, que: "What is the Spanish interrogative for 'how?'?", true: "cómo", false1: "qué", false2: "cuál"},
{num: 156, que: "What is the Spanish interrogative for 'why?'?", true: "por qué", false1: "para qué", false2: "qué"},
{num: 157, que: "What is the Spanish relative pronoun for 'that / which / who'?", true: "que", false1: "quien", false2: "cual"},
{num: 158, que: "What is the Spanish relative pronoun for 'who / whom'?", true: "quien", false1: "que", false2: "cual"},
{num: 159, que: "What is the Spanish relative pronoun for 'which (specific)'?", true: "cual", false1: "que", false2: "quien"},
{num: 160, que: "What is the Spanish relative pronoun for 'whose'?", true: "cuyo", false1: "quien", false2: "que"},
{num: 161, que: "What is the Spanish indefinite pronoun for 'something'?", true: "algo", false1: "alguien", false2: "algún"},
{num: 162, que: "What is the Spanish indefinite pronoun for 'someone'?", true: "alguien", false1: "algo", false2: "algún"},
{num: 163, que: "What is the Spanish indefinite pronoun for 'nothing'?", true: "nada", false1: "nadie", false2: "ninguno"},
{num: 164, que: "What is the Spanish indefinite pronoun for 'no one / nobody'?", true: "nadie", false1: "nada", false2: "ninguno"},
{num: 165, que: "What is the Spanish indefinite pronoun for 'everything'?", true: "todo", false1: "todos", false2: "cada"},
{num: 166, que: "What is the Spanish indefinite pronoun for 'everyone'?", true: "todos", false1: "todo", false2: "cada"},
{num: 167, que: "What is the Spanish phrase for 'each one'?", true: "cada uno", false1: "todo", false2: "alguien"},
{num: 168, que: "What is the Spanish word for 'and'?", true: "y", false1: "e", false2: "o"},
{num: 169, que: "What is the Spanish word for 'and (before i/hi sound)'?", true: "e", false1: "y", false2: "o"},
{num: 170, que: "What is the Spanish word for 'or'?", true: "o", false1: "u", false2: "y"},
{num: 171, que: "What is the Spanish word for 'or (before o/ho sound)'?", true: "u", false1: "o", false2: "y"},
{num: 172, que: "What is the Spanish word for 'but'?", true: "pero", false1: "sino", false2: "mas"},
{num: 173, que: "What is the Spanish word for 'but (rather)'?", true: "sino", false1: "pero", false2: "mas"},
{num: 174, que: "What is the Spanish word for 'but (formal/literary)'?", true: "mas", false1: "pero", false2: "sino"},
{num: 175, que: "What is the Spanish word for 'because'?", true: "porque", false1: "por qué", false2: "para que"},
{num: 176, que: "What is the Spanish phrase for 'so that / in order that'?", true: "para que", false1: "porque", false2: "por qué"},
{num: 177, que: "What is the Spanish word for 'although'?", true: "aunque", false1: "pero", false2: "sin embargo"},
{num: 178, que: "What is the Spanish word for 'if'?", true: "si", false1: "sí", false2: "como"},
{num: 179, que: "What is the Spanish word for 'when'?", true: "cuando", false1: "cuándo", false2: "como"},
{num: 180, que: "What is the Spanish word for 'while'?", true: "mientras", false1: "durante", false2: "cuando"},
{num: 181, que: "What is the Spanish word for 'since / as'?", true: "como", false1: "cuando", false2: "mientras"},
{num: 182, que: "What is the Spanish phrase for 'until'?", true: "hasta que", false1: "desde que", false2: "cuando"},
{num: 183, que: "What is the Spanish phrase for 'before'?", true: "antes de que", false1: "después de que", false2: "mientras"},
{num: 184, que: "What is the Spanish phrase for 'after'?", true: "después de que", false1: "antes de que", false2: "hasta que"},
{num: 185, que: "What is the Spanish phrase for 'however'?", true: "sin embargo", false1: "pero", false2: "aunque"},
{num: 186, que: "What is the Spanish phrase for 'therefore'?", true: "por lo tanto", false1: "porque", false2: "además"},
{num: 187, que: "What is the Spanish phrase for 'thus / so'?", true: "así que", false1: "aunque", false2: "porque"},
{num: 188, que: "What is the Spanish word for 'furthermore / moreover'?", true: "además", false1: "también", false2: "incluso"},
{num: 189, que: "What is the Spanish phrase for 'on the other hand'?", true: "por otro lado", false1: "por lo tanto", false2: "sin embargo"},
{num: 190, que: "What is the Spanish phrase for 'for example'?", true: "por ejemplo", false1: "como", false2: "tal como"},
{num: 191, que: "What is the Spanish phrase for 'that is'?", true: "es decir", false1: "o sea", false2: "por ejemplo"},
{num: 192, que: "What is the Spanish phrase for 'in other words'?", true: "o sea", false1: "es decir", false2: "por ejemplo"},
{num: 193, que: "What is the Spanish phrase for 'in fact'?", true: "de hecho", false1: "en efecto", false2: "realmente"},
{num: 194, que: "What is the Spanish phrase for 'actually'?", true: "en realidad", false1: "realmente", false2: "de hecho"},
{num: 195, que: "What is the Spanish word for 'firstly'?", true: "primero", false1: "primer", false2: "primera"},
{num: 196, que: "What is the Spanish word for 'finally'?", true: "finalmente", false1: "último", false2: "fin"},
{num: 197, que: "What is the Spanish phrase for 'in conclusion'?", true: "en conclusión", false1: "finalmente", false2: "últimamente"},
{num: 198, que: "What is the Spanish phrase for 'on the contrary'?", true: "al contrario", false1: "por contrario", false2: "en contrario"},
{num: 199, que: "What is the Spanish phrase for 'otherwise'?", true: "de lo contrario", false1: "al contrario", false2: "por contrario"},
{num: 200, que: "What is the Spanish phrase for 'similarly'?", true: "de manera similar", false1: "igual", false2: "como"},
{num: 201, que: "What is the Chilean Spanish word for 'cool / awesome'?", true: "bacán", false1: "bueno", false2: "interesante"},
{num: 202, que: "What is the Chilean Spanish word for 'dude / guy (friend)'?", true: "weón", false1: "hombre", false2: "chico"},
{num: 203, que: "What is the Chilean Spanish word for 'thing / stuff'?", true: "weá", false1: "cosa", false2: "asunto"},
{num: 204, que: "What is the Chilean Spanish word for 'money'?", true: "plata", false1: "luca", false2: "dinero"},
{num: 205, que: "What is the Chilean Spanish word for 'thousand pesos'?", true: "luca", false1: "gamba", false2: "peso"},
{num: 206, que: "What is the Chilean Spanish word for 'police officer'?", true: "paco", false1: "policía", false2: "carabinero"},
{num: 207, que: "What is the Chilean Spanish word for 'boring'?", true: "fome", false1: "aburrido", false2: "tedioso"},
{num: 208, que: "What is the Chilean Spanish word for 'crazy / wild'?", true: "cuático", false1: "loco", false2: "raro"},
{num: 209, que: "What is the Chilean Spanish word for 'baby / child'?", true: "guagua", false1: "bebé", false2: "niño"},
{num: 210, que: "What is the Chilean Spanish word for 'job / work'?", true: "pega", false1: "trabajo", false2: "empleo"},
{num: 211, que: "What is the Chilean Spanish phrase for 'What's up? / How's it going?'?", true: "¿Cómo estai?", false1: "¿Qué pasa?", false2: "¿Qué tal?"},
{num: 212, que: "What is the Chilean Spanish phrase for 'I don't care'?", true: "Me da lo mismo", false1: "No me importa", false2: "No me interesa"},
{num: 213, que: "What is the Chilean Spanish word for 'for sure / of course'?", true: "altiro", false1: "claro", false2: "seguro"},
{num: 214, que: "What is the Chilean Spanish phrase for 'right now / immediately'?", true: "al tiro", false1: "ahora", false2: "enseguida"},
{num: 215, que: "What is the Chilean Spanish phrase for 'let's go / come on'?", true: "vamos no má", false1: "vamos", false2: "ándale"},
{num: 216, que: "What is the Chilean Spanish phrase for 'seriously? / for real?'?", true: "¿de veras?", false1: "¿en serio?", false2: "¿verdad?"},
{num: 217, que: "What is the Chilean Spanish phrase for 'it's all good'?", true: "todo bien", false1: "está bien", false2: "todo correcto"},
{num: 218, que: "What is the Chilean Spanish phrase for 'that's awesome'?", true: "qué bacán", false1: "qué bueno", false2: "qué genial"},
{num: 219, que: "What is the Chilean Spanish phrase for 'I'm broke'?", true: "estoy pelao", false1: "no tengo dinero", false2: "estoy pobre"},
{num: 220, que: "What is the Chilean Spanish phrase for 'let's hang out'?", true: "juntémonos", false1: "salimos", false2: "veámonos"},
{num: 221, que: "What is the Chilean Spanish word for 'avocado'?", true: "palta", false1: "aguacate", false2: "avocado"},
{num: 222, que: "What is the Chilean Spanish word for 'strawberry'?", true: "frutilla", false1: "fresa", false2: "mora"},
{num: 223, que: "What is the Chilean Spanish word for 'peach'?", true: "durazno", false1: "melocotón", false2: "ciruela"},
{num: 224, que: "What is the Chilean Spanish word for 'beans'?", true: "porotos", false1: "frijoles", false2: "habichuelas"},
{num: 225, que: "What is the Chilean Spanish word for 'corn on the cob'?", true: "choclo", false1: "maíz", false2: "elote"},
{num: 226, que: "What is the Chilean Spanish word for 'hot dog with toppings'?", true: "completo", false1: "perro caliente", false2: "hot dog"},
{num: 227, que: "What is the Chilean Spanish word for 'boyfriend/girlfriend'?", true: "pololo/polola", false1: "novio/novia", false2: "pareja"},
{num: 228, que: "What is the Chilean Spanish verb for 'to date someone'?", true: "pololear", false1: "salir", false2: "citar"},
{num: 229, que: "What is the Chilean Spanish verb for 'flirt'?", true: "lanzar", false1: "coquetear", false2: "ligar"},
{num: 230, que: "What is the Chilean Spanish word for 'party'?", true: "carrete", false1: "fiesta", false2: "reunión"},
{num: 231, que: "What is the Chilean Spanish verb for 'to party'?", true: "carretear", false1: "fiestear", false2: "celebrar"},
{num: 232, que: "What is the Chilean Spanish phrase for 'friends / crew'?", true: "la mancha", false1: "los amigos", false2: "el grupo"},
{num: 233, que: "What is the Chilean Spanish word for 'car'?", true: "auto", false1: "coche", false2: "carro"},
{num: 234, que: "What is the Chilean Spanish word for 'bus'?", true: "micro", false1: "autobús", false2: "camión"},
{num: 235, que: "What is the Chilean Spanish word for 'cell phone'?", true: "celular", false1: "móvil", false2: "teléfono"},
{num: 236, que: "What is the Chilean Spanish word for 't-shirt'?", true: "polera", false1: "camiseta", false2: "playera"},
{num: 237, que: "What is the Chilean Spanish word for 'sweater'?", true: "polerón", false1: "suéter", false2: "jersey"},
{num: 238, que: "What is the Chilean Spanish verb for 'to understand / get it'?", true: "cachar", false1: "entender", false2: "comprender"},
{num: 239, que: "What is the Chilean Spanish verb for 'to stand someone up'?", true: "plantar", false1: "dejar plantado", false2: "no aparecer"},
{num: 240, que: "What is the Chilean Spanish phrase for 'to be embarrassed'?", true: "dar vergüenza", false1: "tener pena", false2: "estar apenado"},
{num: 241, que: "What is the Chilean Spanish phrase for 'to be in a hurry'?", true: "andar apurado", false1: "tener prisa", false2: "estar rápido"},
{num: 242, que: "What is the Chilean Spanish phrase for 'amazing / excellent'?", true: "la raja", false1: "increíble", false2: "fantástico"},
{num: 243, que: "What is the Chilean Spanish phrase for 'to be broke'?", true: "andar pato", false1: "estar pobre", false2: "no tener plata"},
{num: 244, que: "What is the Chilean Spanish phrase for 'to be tired'?", true: "andar chato", false1: "estar cansado", false2: "estar agotado"},
{num: 245, que: "What is the Chilean Spanish phrase for 'to be fed up'?", true: "estar hasta el loly", false1: "estar harto", false2: "estar cansado"},
{num: 246, que: "What is the Chilean Spanish phrase for 'easy'?", true: "al lote", false1: "fácil", false2: "simple"},
{num: 247, que: "What is the Chilean Spanish phrase for 'for free'?", true: "a la chilena", false1: "gratis", false2: "libre"},
{num: 248, que: "What is the Chilean Spanish exclamation for 'wow!'?", true: "¡huahua!", false1: "¡guau!", false2: "¡vaya!"},
{num: 249, que: "What is the Chilean Spanish exclamation for 'oh my god!'?", true: "¡la weá!", false1: "¡Dios mío!", false2: "¡caray!"},
{num: 250, que: "What is the Chilean Spanish exclamation for 'no way!'?", true: "¡ni cagando!", false1: "¡de ninguna manera!", false2: "¡jamás!"},
{num: 251, que: "What is the Chilean Spanish word for 'of course!'?", true: "¡obvio!", false1: "¡claro!", false2: "¡seguro!"},
{num: 252, que: "What is the Chilean Spanish phrase for 'what a pity'?", true: "qué paja", false1: "qué lástima", false2: "qué pena"},
{num: 253, que: "What is the Spanish word for 'happy'?", true: "feliz", false1: "triste", false2: "enojado"},
{num: 254, que: "What is the Spanish word for 'content / pleased'?", true: "contento", false1: "triste", false2: "nervioso"},
{num: 255, que: "What is the Spanish word for 'excited'?", true: "emocionado", false1: "aburrido", false2: "preocupado"},
{num: 256, que: "What is the Spanish word for 'proud'?", true: "orgulloso", false1: "avergonzado", false2: "celoso"},
{num: 257, que: "What is the Spanish word for 'grateful'?", true: "agradecido", false1: "enfadado", false2: "triste"},
{num: 258, que: "What is the Spanish word for 'optimistic'?", true: "optimista", false1: "pesimista", false2: "realista"},
{num: 259, que: "What is the Spanish word for 'hopeful'?", true: "esperanzado", false1: "desesperado", false2: "preocupado"},
{num: 260, que: "What is the Spanish word for 'loved'?", true: "amado", false1: "odiado", false2: "ignorado"},
{num: 261, que: "What is the Spanish word for 'confident'?", true: "seguro", false1: "inseguro", false2: "nervioso"},
{num: 262, que: "What is the Spanish word for 'sad'?", true: "triste", false1: "feliz", false2: "contento"},
{num: 263, que: "What is the Spanish word for 'angry'?", true: "enojado", false1: "tranquilo", false2: "feliz"},
{num: 264, que: "What is the Spanish word for 'tired'?", true: "cansado", false1: "energético", false2: "activo"},
{num: 265, que: "What is the Spanish word for 'bored'?", true: "aburrido", false1: "interesado", false2: "emocionado"},
{num: 266, que: "What is the Spanish word for 'worried'?", true: "preocupado", false1: "tranquilo", false2: "seguro"},
{num: 267, que: "What is the Spanish word for 'scared'?", true: "asustado", false1: "valiente", false2: "seguro"},
{num: 268, que: "What is the Spanish word for 'nervous'?", true: "nervioso", false1: "tranquilo", false2: "relajado"},
{num: 269, que: "What is the Spanish word for 'disappointed'?", true: "decepcionado", false1: "satisfecho", false2: "contento"},
{num: 270, que: "What is the Spanish word for 'lonely'?", true: "solo", false1: "acompañado", false2: "social"},
{num: 271, que: "What is the Spanish word for 'jealous'?", true: "celoso", false1: "confiado", false2: "seguro"},
{num: 272, que: "What is the Spanish word for 'guilty'?", true: "culpable", false1: "inocente", false2: "libre"},
{num: 273, que: "What is the Spanish word for 'ashamed'?", true: "avergonzado", false1: "orgulloso", false2: "seguro"},
{num: 274, que: "What is the Spanish word for 'anxious'?", true: "ansioso", false1: "tranquilo", false2: "paciente"},
{num: 275, que: "What is the Spanish word for 'frustrated'?", true: "frustrado", false1: "satisfecho", false2: "contento"},
{num: 276, que: "What is the Spanish word for 'confused'?", true: "confundido", false1: "claro", false2: "seguro"},
{num: 277, que: "What is the Spanish word for 'surprised'?", true: "sorprendido", false1: "esperado", false2: "preparado"},
{num: 278, que: "What is the Spanish word for 'shocked'?", true: "impactado", false1: "indiferente", false2: "normal"},
{num: 279, que: "What is the Spanish word for 'sick / ill'?", true: "enfermo", false1: "sano", false2: "saludable"},
{num: 280, que: "What is the Spanish word for 'hungry'?", true: "hambriento", false1: "lleno", false2: "satisfecho"},
{num: 281, que: "What is the Spanish word for 'thirsty'?", true: "sediento", false1: "hidratado", false2: "satisfecho"},
{num: 282, que: "What is the Spanish word for 'sleepy'?", true: "soñoliento", false1: "despierto", false2: "activo"},
{num: 283, que: "What is the Spanish word for 'dizzy'?", true: "mareado", false1: "estable", false2: "firme"},
{num: 284, que: "What is the Spanish word for 'pain'?", true: "dolor", false1: "alivio", false2: "bienestar"},
{num: 285, que: "What is the Spanish word for 'calm'?", true: "tranquilo", false1: "nervioso", false2: "ansioso"},
{num: 286, que: "What is the Spanish word for 'relaxed'?", true: "relajado", false1: "tenso", false2: "estresado"},
{num: 287, que: "What is the Spanish word for 'peaceful'?", true: "pacífico", false1: "alterado", false2: "molesto"},
{num: 288, que: "What is the Spanish word for 'comfortable'?", true: "cómodo", false1: "incómodo", false2: "molesto"},
{num: 289, que: "What is the Spanish phrase for 'in love'?", true: "enamorado", false1: "indiferente", false2: "odiado"},
{num: 290, que: "What is the Spanish word for 'friendly'?", true: "amigable", false1: "hostil", false2: "antipático"},
{num: 291, que: "What is the Spanish word for 'shy'?", true: "tímido", false1: "extrovertido", false2: "social"},
{num: 292, que: "What is the Spanish word for 'embarrassed'?", true: "avergonzado", false1: "orgulloso", false2: "seguro"},
{num: 293, que: "What is the Spanish phrase for 'very happy'?", true: "muy feliz", false1: "poco feliz", false2: "algo feliz"},
{num: 294, que: "What is the Spanish phrase for 'a little sad'?", true: "un poco triste", false1: "muy triste", false2: "extremadamente triste"},
{num: 295, que: "What is the Spanish phrase for 'extremely tired'?", true: "extremadamente cansado", false1: "un poco cansado", false2: "algo cansado"},
{num: 296, que: "What is the Spanish phrase for 'I'm fine'?", true: "Estoy bien", false1: "Estoy mal", false2: "Estoy regular"},
{num: 297, que: "What is the Spanish phrase for 'I'm not feeling well'?", true: "No me siento bien", false1: "Me siento excelente", false2: "Estoy perfecto"},
{num: 298, que: "What is the Spanish phrase for 'How do you feel?'?", true: "¿Cómo te sientes?", false1: "¿Qué piensas?", false2: "¿Qué haces?"},
];
const buttons = ['button1', 'button2', 'button3'];
let currentquetype 
let currentchoiceQuestionIndex = 0;
let currentconjQuestiondex = 0
let Ranswer = 0
let Wanswer = 0
let sentneceque = []
let threechoiceque = []
let conjtableque = [{que: "Hablar - To speak",yo: ["hablo", "hablé", "hablaba", "hablaría", "hablaré"],tu: ["hablas", "hablaste", "hablabas", "hablarías", "hablarás"],el: ["habla", "habló", "hablaba", "hablaría", "hablará"],nos: ["hablamos", "hablamos", "hablábamos", "hablaríamos", "hablaremos"],ellos: ["hablan", "hablaron", "hablaban", "hablarían", "hablarán"]}]

document.addEventListener('DOMContentLoaded', function(){shuffleArray(qna);shuffleArray(conjtableque);startfunc();
});
if(!Ranswer == 0 ) {document.getElementById('ranswer').innerHTML = Ranswer}

document.getElementById('startbtntop').onclick  = ()=> resetAll()

function startfunc(){
document.getElementById('threechoice').style.display = "none";
document.getElementById('conjtable').style.display = "none";
document.getElementById('start').style.display ="";
document.getElementById('startbtn').addEventListener("click", function(){document.getElementById('start').style.display = 'none'; setTimeout(selectquetype(),1000)})
}


function resetAll (){
currentchoiceQuestionIndex = 0;
currentconjQuestiondex = 0
Ranswer = 0
Wanswer = 0
currentquetype = undefined
document.getElementById('ranswer').innerHTML = Ranswer
document.getElementById('wanswer').innerHTML = Wanswer
startfunc()
}

function shuffleArray(array){
    for (let i = array.length - 1; i > 0; i--) {const j = Math.floor(Math.random() * (i + 1));[array[i], array[j]] = [array[j], array[i]];}return array;
}

function selectquetype(){
   /* currentquetype = Math.floor(Math.random() * 10); if (currentquetype < 7 ){} else {disconjtableque()};
    console.log("success?")*/dis3choiceque()
}

function dis3choiceque() {
const currentQ = qna[currentchoiceQuestionIndex];
const answers = [currentQ.true, currentQ.false1, currentQ.false2];
buttons.forEach(btnId => {document.getElementById(btnId).disabled = false;});

    document.getElementById('conjtable').style.display = "none";
    document.getElementById('threechoice').style.display = "";
    document.getElementById("question").innerHTML = currentQ.que;
    
    shuffleArray(answers);
    
    document.getElementById("button1").innerHTML = answers[0];
    document.getElementById("button2").innerHTML = answers[1];
    document.getElementById("button3").innerHTML = answers[2];
    
    document.getElementById("button1").dataset.correct = answers[0] === currentQ.true;
    document.getElementById("button2").dataset.correct = answers[1] === currentQ.true;
    document.getElementById("button3").dataset.correct = answers[2] === currentQ.true;
    
}

function checkAnswer(button){
const buttonbox = document.getElementById("workbox");
if (button.dataset.correct === "true") {
buttons.forEach(btnId => {document.getElementById(btnId).disabled = true;});
workbox.style.backgroundColor = "green";++Ranswer;document.getElementById('ranswer').innerHTML = Ranswer;currentchoiceQuestionIndex++
setTimeout(function(){selectquetype();
buttonbox.style.backgroundColor = "";},1500)}
else {buttonbox.style.backgroundColor = "red"; ++Wanswer; document.getElementById('wanswer').innerHTML = Wanswer
buttons.forEach(btnId => {document.getElementById(btnId).disabled = true;});
setTimeout(function() {buttonbox.style.backgroundColor = "";buttons.forEach(btnId => {document.getElementById(btnId).disabled = false;});}, 1500);}
}

/*function disconjtableque(){
document.getElementById('threechoice').style.display = "none";
document.getElementById('conjtable').style.display = "";
let queindex = shuffleArray(conjtableque)[0];
let alltds = document.getElementsByTagName('td')
let okhello = [queindex.yo,queindex.tu,queindex.el,queindex.nos,queindex.ellos];
let blanked = shuffleArray(okhello.flat()); blanked.splice(0,18);
}

function displayConjTableQuestion() {
    const pronouns = ['yo', 'tu', 'el', 'nos', 'ellos'];
    const tenses = 5; 
    
    pronouns.forEach(pronoun => {
        for (let i = 0; i < tenses; i++) {
            document.querySelector(`#${pronoun} td:nth-child(${i + 1})`).textContent = 
               conjtableque[pronoun][i];}});
}
*/





